# Generated by Django 2.2.5 on 2019-12-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='choices',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
