# Generated by Django 2.2.5 on 2019-12-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20191213_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
